desired_linear_vel: 0.5
lookahead_distance: 0.5
min_lookahead_dist: 0.1
max_lookahead_dist: 3.0
path_length: 30.0
path_type: "s_curve"  # "lineare", "circle", "sinusoid" s_curve
use_case: "turtle"     #turtle or sim
controller_name: "purepursuit"
    
